src/Entity/Employee.php
<?php

namespace App\Entity;

use App\Repository\EmployeeRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EmployeeRepository::class)]
class Employee
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $employee_name = null;

    #[ORM\Column(length: 255)]
    private ?string $employee_username = null;

    #[ORM\Column(length: 255)]
    private ?string $employee_password = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmployeeName(): ?string
    {
        return $this->employee_name;
    }

    public function setEmployeeName(string $employee_name): static
    {
        $this->employee_name = $employee_name;

        return $this;
    }

    public function getEmployeeUsername(): ?string
    {
        return $this->employee_username;
    }

    public function setEmployeeUsername(string $employee_username): static
    {
        $this->employee_username = $employee_username;

        return $this;
    }

    public function getEmployeePassword(): ?string
    {
        return $this->employee_password;
    }

    public function setEmployeePassword(string $employee_password): static
    {
        $this->employee_password = $employee_password;

        return $this;
    }
}

src/Form/EmployeeType.php
<?php

namespace App\Form;

use App\Entity\Employee;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EmployeeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('employee_name')
            ->add('employee_username')
            ->add('employee_password')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Employee::class,
        ]);
    }
}

src/Controller/EmployeeController.php
<?php

namespace App\Controller;

use App\Entity\Employee;
use App\Form\EmployeeType;
use App\Repository\EmployeeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/employee')]
final class EmployeeController extends AbstractController{
    #[Route(name: 'app_employee_index', methods: ['GET'])]
    public function index(EmployeeRepository $employeeRepository): Response
    {
        return $this->render('employee/index.html.twig', [
            'employees' => $employeeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_employee_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $employee = new Employee();
        $form = $this->createForm(EmployeeType::class, $employee);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($employee);
            $entityManager->flush();

            return $this->redirectToRoute('app_employee_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('employee/new.html.twig', [
            'employee' => $employee,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_employee_show', methods: ['GET'])]
    public function show(Employee $employee): Response
    {
        return $this->render('employee/show.html.twig', [
            'employee' => $employee,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_employee_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Employee $employee, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EmployeeType::class, $employee);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_employee_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('employee/edit.html.twig', [
            'employee' => $employee,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_employee_delete', methods: ['POST'])]
    public function delete(Request $request, Employee $employee, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$employee->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($employee);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_employee_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/employee/_delete_form.html.twig
<form method="post" action="{{ path('app_employee_delete', {'id': employee.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ employee.id) }}">
	<button class="w-full bg-red-500 hover:bg-red-600 text-white font-semibold py-2 px-4 rounded-md transition duration-300 ease-in-out">

		Delete
	</button>
</form>

templates/employee/_form.html.twig
{{ form_start(form, {'attr': {'class': 'max-w-md mx-auto bg-white p-8 rounded-lg shadow-lg'}}) }}
    <div class="space-y-4">
        {{ form_row(form.employee_name, {
            'attr': {'class': 'w-full px-4 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500'},
            'label_attr': {'class': 'block text-sm font-medium text-gray-700 mb-1'}
        }) }}
        {{ form_row(form.employee_username, {
            'attr': {'class': 'w-full px-4 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500'},
            'label_attr': {'class': 'block text-sm font-medium text-gray-700 mb-1'}
        }) }}
        {{ form_row(form.employee_password, {
            'attr': {'class': 'w-full px-4 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500'},
            'label_attr': {'class': 'block text-sm font-medium text-gray-700 mb-1'}
        }) }}
        <button class="w-full bg-blue-500 hover:bg-blue-600 text-white font-semibold py-2 px-4 rounded-md transition duration-300 ease-in-out">
            {{ button_label|default('Save') }}
        </button>
    </div>
{{ form_end(form) }}

templates/employee/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Employee
{% endblock %}

{% block body %}
	<nav class="bg-green-800 p-4">
		<div class="container mx-auto flex items-center justify-between">
			<div class="flex space-x-4"></div>
			<div class="flex space-x-4">
				<a href={{ path('app_login') }} class="text-white hover:bg-green-700 px-3 py-2 rounded">
					<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
						<path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15M12 9l-3 3m0 0l3 3m-3-3h12.75"/>
					</svg>
				</a>
			</div>
		</div>
	</nav>

	<div class="min-h-screen bg-gray-100 py-6 flex flex-col justify-center sm:py-12">
		<div class="relative py-3 sm:max-w-xl sm:mx-auto">
			<div class="relative px-4 py-10 bg-white mx-8 md:mx-0 shadow rounded-3xl sm:p-10">
				<div class="max-w-md mx-auto">
					<div class="divide-y divide-gray-200">
						<div class="py-8 text-base leading-6 space-y-4 text-gray-700 sm:text-lg sm:leading-7">
							<h1 class="text-3xl font-bold text-gray-900 mb-8">Edit Employee</h1>

							{{ include('employee/_form.html.twig', {'button_label': 'Update'}) }}

							<div class="flex items-center space-x-4 mt-8">
								<a href="{{ path('app_employee_index') }}" class="text-indigo-600 hover:text-indigo-900 transition duration-150 ease-in-out">← Back to list</a>


								{{ include('employee/_delete_form.html.twig') }}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

templates/employee/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Employee index
{% endblock %}

{% block body %}
	<nav class="bg-green-800 p-4">
		<div class="container mx-auto flex items-center justify-between">
			<div class="flex space-x-4">
				<a href={{ path('app_home') }} class="text-white hover:bg-green-700 px-3 py-2 rounded">
					<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
						<path stroke-linecap="round" stroke-linejoin="round" d="M9 15L3 9m0 0l6-6M3 9h12a6 6 0 010 12h-3"/>
					</svg>
				</a>
			</div>
			<div class="flex space-x-4">
				<a href={{ path('app_login') }} class="text-white hover:bg-green-700 px-3 py-2 rounded">

					<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
						<path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15M12 9l-3 3m0 0l3 3m-3-3h12.75"/>
					</svg>
				</a>
			</div>
		</div>
	</nav>

	<div class="min-h-screen bg-gray-200 py-6">
		<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
			<div class="text-center">
				<h1 class="text-3xl font-bold text-gray-900 mb-8">List of Employees</h1>
			</div>

			<div class="bg-white shadow-xl rounded-lg overflow-hidden">
				<div class="overflow-x-auto">
					<table class="min-w-full divide-y divide-gray-200">
						<thead class="bg-gray-50">
							<tr>
								<th scope="col" class="px-6 py-4 text-left text-sm font-semibold text-gray-900">Employee Name</th>
								<th scope="col" class="px-6 py-4 text-left text-sm font-semibold text-gray-900">Username</th>
								<th scope="col" class="px-6 py-4 text-left text-sm font-semibold text-gray-900">Actions</th>
							</tr>
						</thead>
						<tbody class="divide-y divide-gray-200 bg-white">
							{% for employee in employees %}
								<tr class="transition duration-150 ease-in-out hover:bg-gray-50">
									<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{{ employee.employeeName }}</td>
									<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{{ employee.employeeUsername }}</td>
									<td class="px-6 py-4 whitespace-nowrap text-sm space-x-4">
										<a href="{{ path('app_employee_show', {'id': employee.id}) }}" class="inline-flex items-center px-3 py-1.5 border border-transparent text-sm font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-200">
											View
										</a>
										<a href="{{ path('app_employee_edit', {'id': employee.id}) }}" class="inline-flex items-center px-3 py-1.5 border border-transparent text-sm font-medium rounded-md text-emerald-700 bg-emerald-100 hover:bg-emerald-200">
											Edit
										</a>
									</td>
								</tr>
							{% else %}
								<tr>
									<td colspan="5" class="px-6 py-4 text-sm text-gray-500 text-center">No records found</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
				<div class="p-8 ">
					<a href="{{ path('app_employee_new') }}" class="inline-flex items-center px-4 py-2 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700">
						Create New Employee
					</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/employee/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Employee
{% endblock %}

{% block body %}
	<nav class="bg-green-800 p-4">
		<div class="container mx-auto flex items-center justify-between">
			<div class="flex space-x-4"></div>
			<div class="flex space-x-4">
				<a href={{ path('app_login') }} class="text-white hover:bg-green-700 px-3 py-2 rounded">

					<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
						<path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15M12 9l-3 3m0 0l3 3m-3-3h12.75"/>
					</svg>
				</a>
			</div>
		</div>
	</nav>

	<div class="min-h-screen bg-gray-100 py-6 flex flex-col justify-center sm:py-12">
		<div class="relative py-3 sm:max-w-xl sm:mx-auto">
			<div class="relative px-4 py-10 bg-white mx-8 md:mx-0 shadow rounded-3xl sm:p-10">
				<div class="max-w-md mx-auto">
					<div class="divide-y divide-gray-200">
						<div class="py-8 text-base leading-6 space-y-4 text-gray-700 sm:text-lg sm:leading-7">
							<h1 class="text-3xl font-bold text-gray-900 mb-8">Create new Employee</h1>

							{{ include('employee/_form.html.twig') }}

							<div class="pt-6">
								<a href="{{ path('app_employee_index') }}" class="text-indigo-600 hover:text-indigo-900 transition duration-150 ease-in-out">
									← Back to list
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/employee/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Employee
{% endblock %}

{% block body %}
	<nav class="bg-green-800 p-4">
		<div class="container mx-auto flex items-center justify-between">
			<div class="flex space-x-4"></div>
			<div class="flex space-x-4">
				<a href={{ path('app_login') }} class="text-white hover:bg-green-700 px-3 py-2 rounded">

					<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
						<path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15M12 9l-3 3m0 0l3 3m-3-3h12.75"/>
					</svg>
				</a>
			</div>
		</div>
	</nav>

	<div class="min-h-screen bg-gray-100 py-6 flex flex-col justify-center sm:py-12">
		<div class="relative py-3 sm:max-w-xl sm:mx-auto">
			<div class="relative px-4 py-10 bg-white shadow-lg sm:rounded-3xl sm:p-20">
				<div class="max-w-md mx-auto">
					<div class="divide-y divide-gray-200">
						<h1 class="text-3xl font-semibold text-gray-900 pb-4">Employee Details</h1>
						<div class="py-8 space-y-4">
							<div class="flex justify-between">
								<span class="text-gray-500">ID</span>
								<span class="font-medium">{{ employee.id }}</span>
							</div>
							<div class="flex justify-between">
								<span class="text-gray-500">Name</span>
								<span class="font-medium">{{ employee.employeeName }}</span>
							</div>
							<div class="flex justify-between">
								<span class="text-gray-500">Username</span>
								<span class="font-medium">{{ employee.employeeUsername }}</span>
							</div>
							<div class="flex justify-between">
								<span class="text-gray-500">Password</span>
								<span class="font-medium">{{ employee.employeePassword }}</span>
							</div>
						</div>
						<div class="pt-6 flex items-center space-x-4">
							<a href="{{ path('app_employee_index') }}" class="text-indigo-600 hover:text-indigo-900 transition duration-150 ease-in-out">← Back to list</a>
							<a href="{{ path('app_employee_edit', {'id': employee.id}) }}" class="px-4 py-2 bg-blue-500 hover:bg-blue-600 rounded-md text-sm font-medium text-white">Edit</a>
							{{ include('employee/_delete_form.html.twig') }}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}